# -*- coding: utf-8 -*-
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: requirements-txt-fixer
      name: requirements.txt files
      types: [file]
      exclude_types: ['image']
    - id: debug-statements
      name: debugging statements
      language: python
      types: [file, python]
      exclude_types: ['image']
    - id: trailing-whitespace
      name: trailing whitespace
      language: python
      types: [file]
      exclude_types: ['image', 'binary', 'executable']
    - id: end-of-file-fixer
      name: file EOF markers
      language: python
      types: [file]
      exclude_types: ['image', 'binary', 'executable']
    - id: check-yaml
      name: .yaml structure
      language: python
      args: ['--unsafe']
    - id: check-toml
      name: .toml structure
    - id: check-merge-conflict
      name: merge conflicts
    - id: fix-encoding-pragma
      name: encoding pragma
      language: python
      types: [file]
      exclude_types: ['image', 'binary', 'executable']
    - id: name-tests-test
      name: test naming convention
      language: python
      types: [file]
      exclude_types: ['image', 'binary', 'executable']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.2'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language: python
        types: [ file, python ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --strict-equality, --disallow-incomplete-defs]
ci:
  autoupdate_branch: "unstable"
  autofix_prs: true
  autoupdate_commit_msg: "ci: weekly check."
  autoupdate_schedule: weekly
  autofix_commit_msg: "ci: correct from checks."
default_language_version:
  python: python3.10
